-- Nama database : PERPUSTAKAAN
-- Software DBMS : ORACLE APEX
-- Bagian        : CREATE VIEW PART_1

-- Membuat beberapa view dengan beberapa kondisi part_1
-- PENERAPAN JOIN part-1
-- Membuat view V_PEMINJAMAN_BUKU  -> pinjam buku 
CREATE VIEW V_PEMINJAMAN_BUKU  AS
SELECT A.ID_PINJAM KODE_PINJAM,
    B.JUDUL_BUKU  BUKU , 
    B.ID_BUKU  KODE_BUKU , 
    C.NAMA_LENGKAP PEMINJAM, 
    C.ID_MEMBER KODE_MEMBER, 
    D.NAMA_LENGKAP PEMBERI,
    D.ID_STAFF KODE_PEMBER, 
    A.TGL_PINJAM, 
    A.TGL_KEMBALI
FROM PEMINJAMAN A
JOIN BUKU  B ON B.ID_BUKU  = A.ID_BUKU 
JOIN MEMBER C ON C.ID_MEMBER = A.ID_MEMBER
JOIN STAFF D ON D.ID_STAFF = A.ID_STAFF
ORDER BY KODE_PINJAM ASC;

-- Membuat view V_REKAP_PENGUNJUNG -> rekap pengunjung
CREATE VIEW V_REKAP_PENGUNJUNG AS
SELECT A.ID_PENGUNJUNG KODE_PENGUNJUNG, 
    B.NAMA_LENGKAP MEMBER,
    CASE
        WHEN GENDER = '0' THEN 'PEREMPUAN'
        WHEN GENDER = '1' THEN 'LAKI-LAKI'
        ELSE 'TIDAK KETAHUI'
    END AS GENDER,
    B.ID_MEMBER KODE_MEMBER,
    A.TGL_KUNJUNGAN
FROM PENGUNJUNG A
JOIN MEMBER B ON B.ID_MEMBER = A.ID_MEMBER
ORDER BY KODE_PENGUNJUNG ASC; 