-- Nama database : PERPUSTAKAAN
-- Software DBMS : ORACLE APEX
-- Bagian        : CREATE TABEL

-- Membuat beberepa tabel pada database PERPUSTAKAAN
-- Membuat tabel BUKU 
CREATE TABLE BUKU  (
    ID_BUKU  CHAR(6) CONSTRAINT PK_BUKU PRIMARY KEY,
    JUDUL_BUKU  VARCHAR2(255),
    TAHUN_TERBIT CHAR(4),
    ISBN VARCHAR2(45),
    PENGARANG VARCHAR2(100),
    PENERBIT VARCHAR2(50)
);

-- Membuat tabel STAFF
CREATE TABLE STAFF (
    ID_STAFF CHAR(6) CONSTRAINT PK_STAFF PRIMARY KEY,
    NAMA_LENGKAP VARCHAR2(100),
    USERNAME VARCHAR2(50),
    PASSWORD VARCHAR2(50),
    GENDER CHAR(1),
    ALAMAT VARCHAR2(255),
    NO_TELP VARCHAR2(13),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- Membuat tabel MEMBER
CREATE TABLE MEMBER (
    ID_MEMBER CHAR(7) CONSTRAINT PK_MEMBER PRIMARY KEY,
    NAMA_LENGKAP VARCHAR2(100),
    GENDER CHAR(1),
    ALAMAT VARCHAR2(255),
    NO_TELP VARCHAR2(13),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- Membuat tabel PENGUNJUNG
CREATE TABLE PENGUNJUNG (
    ID_PENGUNJUNG CHAR(6) CONSTRAINT PK_PENGUNJUNG PRIMARY KEY,
    ID_MEMBER CHAR(7) REFERENCES MEMBER(ID_MEMBER),
    TGL_KUNJUNGAN DATE
);

-- Membuat tabel PEMINJAMAN
CREATE TABLE PEMINJAMAN (
    ID_PINJAM CHAR(6) CONSTRAINT PK_PINJAM PRIMARY KEY,
    ID_BUKU  CHAR(6) REFERENCES BUKU (ID_BUKU ),
    TGL_PINJAM DATE,
    TGL_KEMBALI DATE,
    ID_STAFF CHAR(6) REFERENCES STAFF(ID_STAFF),
    ID_MEMBER CHAR(7) REFERENCES MEMBER(ID_MEMBER)
);

-- Membuat tabel PENGEMBALIAN
CREATE TABLE PENGEMBALIAN (
    ID_KEMBALI CHAR(6) CONSTRAINT PK_KEMBALI PRIMARY KEY,
    TGL_PENGEMBALIAN DATE,
    ID_PINJAM CHAR(6) REFERENCES PEMINJAMAN(ID_PINJAM),
    DENDA NUMBER(6),
    ID_STAFF CHAR(6) REFERENCES STAFF(ID_STAFF),
    ID_MEMBER CHAR(7) REFERENCES MEMBER(ID_MEMBER)
);
