-- Nama database : PERPUSTAKAAN
-- Software DBMS : ORACLE APEX
-- Bagian        : CREATE TABEL

-- Membuat beberepa tabel pada database PERPUSTAKAAN
-- Membuat tabel BUKU 
CREATE TABLE BUKU  (
    ID_BUKU  CHAR(6) CONSTRAINT PK_BUKU PRIMARY KEY,
    JUDUL_BUKU  VARCHAR2(255),
    TAHUN_TERBIT CHAR(4),
    ISBN VARCHAR2(45),
    PENGARANG VARCHAR2(100),
    PENERBIT VARCHAR2(50)
);

-- Membuat tabel STAFF
CREATE TABLE STAFF (
    ID_STAFF CHAR(6) CONSTRAINT PK_STAFF PRIMARY KEY,
    NAMA_LENGKAP VARCHAR2(100),
    USERNAME VARCHAR2(50),
    PASSWORD VARCHAR2(50),
    GENDER CHAR(1),
    ALAMAT VARCHAR2(255),
    NO_TELP VARCHAR2(13),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- Membuat tabel MEMBER
CREATE TABLE MEMBER (
    ID_MEMBER CHAR(7) CONSTRAINT PK_MEMBER PRIMARY KEY,
    NAMA_LENGKAP VARCHAR2(100),
    GENDER CHAR(1),
    ALAMAT VARCHAR2(255),
    NO_TELP VARCHAR2(13),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- Membuat tabel PENGUNJUNG
CREATE TABLE PENGUNJUNG (
    ID_PENGUNJUNG CHAR(6) CONSTRAINT PK_PENGUNJUNG PRIMARY KEY,
    ID_MEMBER CHAR(7) REFERENCES MEMBER(ID_MEMBER),
    TGL_KUNJUNGAN DATE
);

-- Membuat tabel PEMINJAMAN
CREATE TABLE PEMINJAMAN (
    ID_PINJAM CHAR(6) CONSTRAINT PK_PINJAM PRIMARY KEY,
    ID_BUKU  CHAR(6) REFERENCES BUKU (ID_BUKU ),
    TGL_PINJAM DATE,
    TGL_KEMBALI DATE,
    ID_STAFF CHAR(6) REFERENCES STAFF(ID_STAFF),
    ID_MEMBER CHAR(7) REFERENCES MEMBER(ID_MEMBER)
);

-- Membuat tabel PENGEMBALIAN
CREATE TABLE PENGEMBALIAN (
    ID_KEMBALI CHAR(6) CONSTRAINT PK_KEMBALI PRIMARY KEY,
    TGL_PENGEMBALIAN DATE,
    ID_PINJAM CHAR(6) REFERENCES PEMINJAMAN(ID_PINJAM),
    DENDA NUMBER(6),
    ID_STAFF CHAR(6) REFERENCES STAFF(ID_STAFF),
    ID_MEMBER CHAR(7) REFERENCES MEMBER(ID_MEMBER)
);

-- Bagian        : CREATE VIEW

-- Membuat beberapa view dengan beberapa kondisi
-- PENERAPAN JOIN
-- Membuat view V_PEMINJAMAN_BUKU  -> pinjam buku 
CREATE VIEW V_PEMINJAMAN_BUKU  AS
SELECT A.ID_PINJAM KODE_PINJAM,
    B.JUDUL_BUKU  BUKU , 
    B.ID_BUKU  KODE_BUKU , 
    C.NAMA_LENGKAP PEMINJAM, 
    C.ID_MEMBER KODE_MEMBER, 
    D.NAMA_LENGKAP PEMBERI,
    D.ID_STAFF KODE_PEMBERI, 
    A.TGL_PINJAM, 
    A.TGL_KEMBALI
FROM PEMINJAMAN A
JOIN BUKU  B ON B.ID_BUKU  = A.ID_BUKU 
JOIN MEMBER C ON C.ID_MEMBER = A.ID_MEMBER
JOIN STAFF D ON D.ID_STAFF = A.ID_STAFF
ORDER BY KODE_PINJAM ASC;

-- Membuat view V_REKAP_PENGUNJUNG -> rekap pengunjung
CREATE VIEW V_REKAP_PENGUNJUNG AS
SELECT A.ID_PENGUNJUNG KODE_PENGUNJUNG, 
    B.NAMA_LENGKAP MEMBER,
    CASE
        WHEN GENDER = '0' THEN 'PEREMPUAN'
        WHEN GENDER = '1' THEN 'LAKI-LAKI'
        ELSE 'TIDAK KETAHUI'
    END AS GENDER,
    B.ID_MEMBER KODE_MEMBER,
    A.TGL_KUNJUNGAN
FROM PENGUNJUNG A
JOIN MEMBER B ON B.ID_MEMBER = A.ID_MEMBER
ORDER BY KODE_PENGUNJUNG ASC; 

-- Membuat view V_PENGEMBALIAN_BUKU  -> pengembalian buku  
CREATE VIEW V_PENGEMBALIAN_BUKU  AS
SELECT A.ID_KEMBALI KODE_KEMBALI, 
    B.BUKU, 
    B.KODE_BUKU,
    C.NAMA_LENGKAP PEMINJAM, 
    C.ID_MEMBER KODE_PEMINJAM,
    D.NAMA_LENGKAP PENERIMA, 
    D.ID_STAFF KODE_PENERIMA,
    A.TGL_PENGEMBALIAN, 
    A.DENDA
FROM PENGEMBALIAN A
JOIN V_PEMINJAMAN_BUKU  B ON B.KODE_PINJAM = A.ID_PINJAM
JOIN MEMBER C ON C.ID_MEMBER = A.ID_MEMBER
JOIN STAFF D ON D.ID_STAFF = A.ID_STAFF
ORDER BY KODE_KEMBALI ASC;

-- PENERAPAN FUNGSI ARITMATIKA
-- Misalkan telat mengembalikan buku dan telah
-- lewat selama 5 hari. Jika telat mengembalikan
-- maka akan diberikan denda sebesar Rp. 5000.
-- Kemudian jika melewati tanggal pengembalian
-- maka akan ditambahkan Rp. 1.0000 pada denda
-- peminjam buku yang bersangkutan setiap 
-- terlewat perharinya.

-- Misalkan MEMBER dengan ID_MEMBER 'MBR0011' telat
-- mengembalikan buku dan telah lewat selama 5 hari

CREATE VIEW V_TELAT_MENGEMBALIKAN_5_HARI AS
SELECT A.ID_KEMBALI KODE_KEMBALI,
    B.BUKU,
    B.KODE_BUKU,
    C.NAMA_LENGKAP PEMINJAM,
    C.ID_MEMBER KODE_PEMINJAM,
    D.NAMA_LENGKAP PENERIMA,
    D.ID_STAFF KODE_PENERIMA,
    B.TGL_KEMBALI+5 TGL_PENGEMBALIAN,
    A.DENDA+5000+(5*1000) DENDA
FROM PENGEMBALIAN A
JOIN V_PEMINJAMAN_BUKU B ON B.KODE_PINJAM = A.ID_PINJAM
JOIN MEMBER C ON C.ID_MEMBER = A.ID_MEMBER
JOIN STAFF D ON D.ID_STAFF = A.ID_STAFF
WHERE C.ID_MEMBER LIKE 'MBR0011';

-- QUERY DENGAN PENERAPAN FUNGSI TEKS
-- Mengambil data pada tabel MEMBER dan PENGUNJUNG kemudian
-- menambahkan teks 'mengunjungi perpustakaan pada tanggal'.

CREATE VIEW V_PERNYATAAN AS
SELECT B.NAMA_LENGKAP ||  ' mengunjungi perpustakaan pada tanggal ' || TGL_KUNJUNGAN AS PERNYATAAN
FROM PENGUNJUNG A
JOIN MEMBER B ON B.ID_MEMBER = A.ID_MEMBER
ORDER BY ID_PENGUNJUNG;

-- QUERY DENGAN KONDISI WHERE DAN LIKE
-- Mencari pengunjung dan kapan melakukan kunjungan yang
-- memiliki alamat di daerah berawalan 'B' dan 'C'.

CREATE VIEW V_PENGUNJUNG_ASAL_B_DAN_C AS
SELECT A.ID_PENGUNJUNG AS KODE_PENGUNJUNG,
    B.NAMA_LENGKAP AS MEMBER,
    CASE
        WHEN B.GENDER = '0' THEN 'PEREMPUAN'
        WHEN B.GENDER = '1' THEN 'LAKI-LAKI'
        ELSE 'TIDAK KETAHUI'
    END AS GENDER,
    B.ID_MEMBER AS KODE_MEMBER,
    B.ALAMAT,
    A.TGL_KUNJUNGAN
FROM PENGUNJUNG A
JOIN MEMBER B ON B.ID_MEMBER = A.ID_MEMBER
WHERE B.ALAMAT LIKE 'B%' OR B.ALAMAT LIKE 'C%'
ORDER BY TGL_KUNJUNGAN ASC;

-- PENERAPAN GROUP BY
-- Mengambil data berapa banyak pengunjung
-- yang berkunjung sesuai dengan tanggalnya.

CREATE VIEW V_BANYAK_PENGUNJUNG AS
SELECT TGL_KUNJUNGAN,
    COUNT(ID_PENGUNJUNG) || ' orang' AS BANYAK_PENGUNJUNG
FROM PENGUNJUNG
GROUP BY TGL_KUNJUNGAN
ORDER BY TGL_KUNJUNGAN ASC;

-- Bagian        : INSERT DATA

-- Memasukkan beberapa data pada beberapa tabel
-- Memasukkan data buku pada tabel BUKU
INSERT ALL
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0001', 'Akuntansi Pengantar 1', '2009', '978-979-107-882-5', 'Supardi', 'Gava Media')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0002', 'Aplikasi Klinis Induk Ovulasi & Stimulasi Ovariu', '2013', '978-979-328-876-5', 'Samsulhadi', 'Sagung Seto')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0003', 'Aplikasi Praktis Asuhan Keperawatan Keluarga', '2012', '978-602-867-404-1', 'Komang Ayu Heni', 'Sagung Seto')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0004', 'Bangsa gagal ; Mencari identitas kebangsaan', '2008', '978-979-128-365-6', 'Nasrudin Anshoriy', 'LKiS')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0005', 'Biografi Gus Dur ; The Authorized Biography of KH. Abdurrahman Wahid (Soft Cover)', '2011', '978-979-338-125-1', 'Greg Barton', 'LKiS')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0006', 'Cedera Kepala', '2013', '978-602-867-497-3', 'M. Z. Arifin', 'Sagung Seto')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0007', 'Kolaborasi PHP 5 dan Mysql untuk pengembangan website + cd', '2014', '978-979-294-344-3', 'Eko Priya Utomo', 'Andi Offset')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0008', 'Lembaga keuangan Islam', '2015', '978-602-873-012-9', 'Nurul Huda', 'PRENADA MEDIA GRUP')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0009', 'Strategic Management', '2016', '978-979-769-632-0', 'Sofjan Assauri', 'Rajagrafindo Persada')
    INTO BUKU (ID_BUKU, JUDUL_BUKU, TAHUN_TERBIT, ISBN, PENGARANG, PENERBIT) 
    VALUES ('BK0010', 'Tuntunan Praktis : Pengembangan Aplikasi Sistem Informasi Geografis berbasis Dekstop dan Web + CD', '2009', '978-979-107-870-2', 'Riyanto', 'Gava Media')
SELECT 1 FROM DUAL;

-- Memasukkan data staff pada tabel STAFF
INSERT ALL
    INTO STAFF (ID_STAFF, NAMA_LENGKAP, USERNAME, PASSWORD, GENDER, ALAMAT, NO_TELP, CREATED_AT) 
    VALUES ('ADM001', 'Ali', 'ali', 'ali', '1', 'Nanggeleng', '081234567890', TO_DATE('05-06-2024', 'DD-MM-YYYY'))
    INTO STAFF (ID_STAFF, NAMA_LENGKAP, USERNAME, PASSWORD, GENDER, ALAMAT, NO_TELP, CREATED_AT) 
    VALUES ('ADM002', 'Ahmad', 'ahmad', 'ahmad', '1', 'Ciaul', '081298765432', TO_DATE('05-06-2024', 'DD-MM-YYYY'))
    INTO STAFF (ID_STAFF, NAMA_LENGKAP, USERNAME, PASSWORD, GENDER, ALAMAT, NO_TELP, CREATED_AT) 
    VALUES ('ADM003', 'Hasan', 'hasan', 'hasan', '1', 'Cikole', '081212345678', TO_DATE('05-06-2024', 'DD-MM-YYYY'))
    INTO STAFF (ID_STAFF, NAMA_LENGKAP, USERNAME, PASSWORD, GENDER, ALAMAT, NO_TELP, CREATED_AT) 
    VALUES ('ADM004', 'Faqih', 'faqih', 'faqih', '1', 'Baros', '081278945612', TO_DATE('05-06-2024', 'DD-MM-YYYY'))
    INTO STAFF (ID_STAFF, NAMA_LENGKAP, USERNAME, PASSWORD, GENDER, ALAMAT, NO_TELP, CREATED_AT) 
    VALUES ('ADM005', 'Hilman', 'hilman', 'hilman', '1', 'Dayeuhluhur', '081256789012', TO_DATE('05-06-2024', 'DD-MM-YYYY'))
SELECT 1 FROM DUAL;

-- Memasukkan data member pada tabel MEMBER
INSERT ALL
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0001', 'Agus Santoso', '1', 'Nanggeleng', '081234567890', TO_DATE('06-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0002', 'Budi Hartono', '1', 'Baros', '081234567891', TO_DATE('08-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0003', 'Citra Dewi', '0', 'Cikole', '081234567892', TO_DATE('10-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0004', 'Dewi Lestari', '0', 'Ciaul', '081234567893', TO_DATE('12-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0005', 'Eka Putra', '1', 'Limusnunggal', '081234567894', TO_DATE('14-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0006', 'Fajar Nugroho', '1', 'Bhayangkara', '081234567895', TO_DATE('16-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0007', 'Gina Amalia', '0', 'Kebonjati', '081234567896', TO_DATE('18-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0008', 'Hendra Kurniawan', '1', 'Citamiang', '081234567897', TO_DATE('20-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0009', 'Indra Gunawan', '1', 'Gunungpuyuh', '081234567898', TO_DATE('22-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0010', 'Joko Susanto', '1', 'Lembursitu', '081234567899', TO_DATE('24-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0011', 'Kartini', '0', 'Benteng', '081234567800', TO_DATE('26-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0012', 'Lina Marlina', '0', 'Nanggeleng', '081234567801', TO_DATE('28-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0013', 'Maman Suparman', '1', 'Baros', '081234567802', TO_DATE('30-06-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0014', 'Nani Wijaya', '0', 'Cikole', '081234567803', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0015', 'Oki Setiana Dewi', '0', 'Ciaul', '081234567804', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0016', 'Putu Ayu', '0', 'Limusnunggal', '081234567805', TO_DATE('05-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0017', 'Qori Izzatul', '0', 'Bhayangkara', '081234567806', TO_DATE('06-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0018', 'Rina Wijaya', '0', 'Kebonjati', '081234567807', TO_DATE('07-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0019', 'Siti Aminah', '0', 'Citamiang', '081234567808', TO_DATE('08-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0020', 'Taufik Hidayat', '1', 'Gunungpuyuh', '081234567809', TO_DATE('09-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0021', 'Umi Kalsum', '0', 'Lembursitu', '081234567810', TO_DATE('10-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0022', 'Vina Melinda', '0', 'Benteng', '081234567811', TO_DATE('11-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0023', 'Wahyu Nugroho', '1', 'Nanggeleng', '081234567812', TO_DATE('12-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0024', 'Xaverius Adi', '1', 'Baros', '081234567813', TO_DATE('13-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0025', 'Yuniarti Dewi', '0', 'Cikole', '081234567814', TO_DATE('14-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0026', 'Zaki Kurniawan', '1', 'Ciaul', '081234567815', TO_DATE('15-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0027', 'Ahmad Fauzan', '1', 'Limusnunggal', '081234567816', TO_DATE('16-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0028', 'Bella Saphira', '0', 'Bhayangkara', '081234567817', TO_DATE('17-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0029', 'Chandra Wijaya', '1', 'Kebonjati', '081234567818', TO_DATE('18-07-2024', 'DD-MM-YYYY'))
    INTO MEMBER (ID_MEMBER, NAMA_LENGKAP, GENDER, ALAMAT, NO_TELP, CREATED_AT) VALUES ('MBR0030', 'Desi Ratnasari', '0', 'Citamiang', '081234567819', TO_DATE('19-07-2024', 'DD-MM-YYYY'))
SELECT 1 FROM DUAL;

-- Memasukkan data pengunjung pada tabel PENGUNJUNG
-- Pengunjung hari Senin tgl 1 Juli 2024
INSERT ALL
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0001', 'MBR0011', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0002', 'MBR0012', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0003', 'MBR0015', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0004', 'MBR0030', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0005', 'MBR0018', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0006', 'MBR0022', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0007', 'MBR0007', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0008', 'MBR0008', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0009', 'MBR0019', TO_DATE('01-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0010', 'MBR0027', TO_DATE('01-07-2024', 'DD-MM-YYYY'))

-- Pengunjung hari Selasa tgl 2 Juli 2024
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0011', 'MBR0023', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0012', 'MBR0001', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0013', 'MBR0024', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0014', 'MBR0006', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0015', 'MBR0020', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0016', 'MBR0029', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0017', 'MBR0016', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0018', 'MBR0004', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0019', 'MBR0028', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0020', 'MBR0013', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0021', 'MBR0002', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0022', 'MBR0014', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0023', 'MBR0010', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0024', 'MBR0003', TO_DATE('02-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0025', 'MBR0005', TO_DATE('02-07-2024', 'DD-MM-YYYY'))

-- Pengunjung hari Rabu tgl 3 Juli 2024
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0026', 'MBR0009', TO_DATE('03-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0027', 'MBR0023', TO_DATE('03-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0028', 'MBR0024', TO_DATE('03-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0029', 'MBR0017', TO_DATE('03-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0030', 'MBR0003', TO_DATE('03-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0031', 'MBR0012', TO_DATE('03-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0032', 'MBR0014', TO_DATE('03-07-2024', 'DD-MM-YYYY'))

-- Pengunjung hari Kamis tgl 4 Juli 2024
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0033', 'MBR0001', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0034', 'MBR0015', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0035', 'MBR0008', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0036', 'MBR0010', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0037', 'MBR0019', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0038', 'MBR0002', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0039', 'MBR0016', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0040', 'MBR0013', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0041', 'MBR0012', TO_DATE('04-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0042', 'MBR0018', TO_DATE('04-07-2024', 'DD-MM-YYYY'))

-- Pengunjung hari Jumat tgl 5 Juli 2024
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0043', 'MBR0007', TO_DATE('05-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0044', 'MBR0011', TO_DATE('05-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0045', 'MBR0025', TO_DATE('05-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0046', 'MBR0009', TO_DATE('05-07-2024', 'DD-MM-YYYY'))
    INTO PENGUNJUNG (ID_PENGUNJUNG, ID_MEMBER, TGL_KUNJUNGAN) VALUES ('PG0047', 'MBR0023', TO_DATE('05-07-2024', 'DD-MM-YYYY'))
SELECT 1 FROM DUAL;

-- Memasukkan data pinjam buku pada tabel PEMINJAMAN
INSERT ALL
    INTO PEMINJAMAN (ID_PINJAM, ID_BUKU, TGL_PINJAM, TGL_KEMBALI, ID_STAFF, ID_MEMBER) VALUES ('PJ0001', 'BK0007', TO_DATE('01-07-2024', 'DD-MM-YYYY'), TO_DATE('08-07-2024', 'DD-MM-YYYY'), 'ADM001', 'MBR0011')
    INTO PEMINJAMAN (ID_PINJAM, ID_BUKU, TGL_PINJAM, TGL_KEMBALI, ID_STAFF, ID_MEMBER) VALUES ('PJ0002', 'BK0003', TO_DATE('01-07-2024', 'DD-MM-YYYY'), TO_DATE('08-07-2024', 'DD-MM-YYYY'), 'ADM001', 'MBR0012')
    INTO PEMINJAMAN (ID_PINJAM, ID_BUKU, TGL_PINJAM, TGL_KEMBALI, ID_STAFF, ID_MEMBER) VALUES ('PJ0003', 'BK0007', TO_DATE('02-07-2024', 'DD-MM-YYYY'), TO_DATE('09-07-2024', 'DD-MM-YYYY'), 'ADM002', 'MBR0023')
    INTO PEMINJAMAN (ID_PINJAM, ID_BUKU, TGL_PINJAM, TGL_KEMBALI, ID_STAFF, ID_MEMBER) VALUES ('PJ0004', 'BK0006', TO_DATE('04-07-2024', 'DD-MM-YYYY'), TO_DATE('11-07-2024', 'DD-MM-YYYY'), 'ADM004', 'MBR0001')
    INTO PEMINJAMAN (ID_PINJAM, ID_BUKU, TGL_PINJAM, TGL_KEMBALI, ID_STAFF, ID_MEMBER) VALUES ('PJ0005', 'BK0008', TO_DATE('05-07-2024', 'DD-MM-YYYY'), TO_DATE('12-07-2024', 'DD-MM-YYYY'), 'ADM005', 'MBR0009')
SELECT 1 FROM DUAL;

-- Memasukkan data pengembalian buku pada tabel PENGEMBALIAN
INSERT ALL
    INTO PENGEMBALIAN (ID_KEMBALI, TGL_PENGEMBALIAN, ID_PINJAM, DENDA, ID_STAFF, ID_MEMBER) VALUES ('PB0001', TO_DATE('05-07-2024', 'DD-MM-YYYY'), 'PJ0001', 0, 'ADM005', 'MBR0011')
    INTO PENGEMBALIAN (ID_KEMBALI, TGL_PENGEMBALIAN, ID_PINJAM, DENDA, ID_STAFF, ID_MEMBER) VALUES ('PB0002', TO_DATE('04-07-2024', 'DD-MM-YYYY'), 'PJ0002', 0, 'ADM004', 'MBR0012')
    INTO PENGEMBALIAN (ID_KEMBALI, TGL_PENGEMBALIAN, ID_PINJAM, DENDA, ID_STAFF, ID_MEMBER) VALUES ('PB0003', TO_DATE('05-07-2024', 'DD-MM-YYYY'), 'PJ0003', 0, 'ADM005', 'MBR0023')
SELECT 1 FROM DUAL;
