-- Nama database : PERPUSTAKAAN
-- Software DBMS : ORACLE APEX
-- Bagian        : DELETE ALL TABLE AND VIEW

-- DROP ALL TABLE
DROP TABLE PENGEMBALIAN;
DROP TABLE PENGUNJUNG;
DROP TABLE PEMINJAMAN;
DROP TABLE BUKU;
DROP TABLE MEMBER;
DROP TABLE STAFF;

-- DROP ALL VIEW
DROP VIEW V_BANYAK_PENGUNJUNG;
DROP VIEW V_PEMINJAMAN_BUKU;
DROP VIEW V_PENGEMBALIAN_BUKU;
DROP VIEW V_REKAP_PENGUNJUNG;
DROP VIEW V_PENGUNJUNG_ASAL_B_DAN_C;
DROP VIEW V_PERNYATAAN;
DROP VIEW V_TELAT_MENGEMBALIKAN_5_HARI;
